# Development environment

FROM node:12-alpine

# Do not use 'COPY . .' to copy all files, as some are only needed in the final image.
# Copying all files will force a build even if no client files have been modified

# Install
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY sync-package-lock ./
RUN npm install

# Development server
COPY src ./src
COPY public ./public
COPY .eslintrc.js ./
COPY tsconfig.json ./
COPY webpack.config.ts ./

# This is responsible of copying node_modules and package-lock.json to host machine
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint.sh" ]

CMD [ "npm", "start" ]
