FROM node:12-alpine

# Set app directory
WORKDIR /app

# Env
ENV NODE_OPTIONS=--max_old_space_size=4096

# Install dependencies
COPY package.json ./
COPY nodemon.json ./
COPY tsconfig.json ./
COPY sync-package-lock ./

# Copy app (only files of dockerignore will be ignored)
COPY . .

# If package-lock.json is not found in previous step, it will be created in the following npm install
RUN npm install
RUN npm run build
# # Migration should be here
# RUN npm run migrate

# This is responsible of copying node_modules and package-lock.json to host machine
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# TODO: Expose app ports. First internal. Second external (exposed)
EXPOSE 3000

ENTRYPOINT [ "/docker-entrypoint.sh" ]
# CMD is not executed in build step
CMD [ "npm", "run", "serve" ]
