FROM node:12-alpine

# Set app directory
WORKDIR /app

# Env
ENV NODE_OPTIONS=--max_old_space_size=4096

# Copy dependencies files
COPY package.json ./
COPY sync-package-lock ./

# If package-lock.json is not found in previous step, it will be created in the following npm install
RUN npm install

# Copy build files
COPY nodemon.json ./
COPY tsconfig.json ./
COPY src ./src/

RUN npm run build

# Copy migration files
COPY database ./
# This is responsible of copying node_modules and package-lock.json to host machine
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh


ENTRYPOINT [ "/docker-entrypoint.sh" ]

# CMD is not executed when command is defined in docker compose
CMD [ "npm", "run", "serve" ]
