version: '3.4'
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'psswd'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'psswd'
    ports:
      # <Port exposed> : <Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      # Where our data will be persisted
      - database-data:/var/lib/mysql
  backend:
    depends_on:
      - database
    restart: unless-stopped
    build:
      context: ../backend/
      dockerfile: Dockerfile.dev
    working_dir: /app
    environment:
        # Depends on 'database' docker service configuration
        MYSQL_HOST: 'database' # Docker service called 'database'
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'admin'
        MYSQL_PASSWORD: 'psswd'
        MYSQL_PORT: '3306'
        NODE_ENV: development
        JWT_SECRET: 87e3459aec28ec448228d4f990e80f14657daefc7f01a7146e1149663b30719d
        REFRESH_JWT_SECRET: 6c2723ab022250723988e5cf38e90908be10e82ee2ce802747d279f4dd7bc823
    volumes:
        - "../backend/node_modules:/app/node_modules_for_local_development"
        - "../backend/sync-package-lock:/app/sync-package-lock"
        - "../backend/src:/app/src"
    ports:
        - "3000:3000"
    command: "npm run develop"
  frontend:
    depends_on:
      - backend
    restart: unless-stopped
    build:
      context: ../frontend/
      dockerfile: Dockerfile.dev
    working_dir: /app
    environment:
        - NODE_ENV=development
    volumes:
        - "../frontend/node_modules:/app/node_modules_for_local_development"
        - "../frontend/sync-package-lock:/app/sync-package-lock"
        - "../frontend/src:/app/src"
    ports:
        - "3010:3010"
    command: "npm run develop"
# Names our volume
volumes:
  database-data:
  # backend-public:
  #     driver_opts:
  #         type: "none"
  #         device: "${PWD}/data/backend/public"
  #         o: "bind"